# Etapa 1: Construção da aplicação com Node.js
FROM node:18 AS build-stage

# Definir o diretório de trabalho no contêiner
WORKDIR /app

# Copiar os arquivos package.json e package-lock.json
COPY package*.json ./

# Instalar dependências
RUN npm install

# Copiar o restante do código da aplicação
COPY . .

# Comando padrão para iniciar o Nginx
CMD ["vite --port 80"]   
