services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "3001:3000"

    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "8081:80"
