services:
    server:
        container_name: server
        build:
            context: ./server
        ports:
            - "3000:3000"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.server.rule=Host(`coolify.io`) && PathPrefix(`/server`)"
            - "traefik.http.routers.server.entrypoints=http"
            - "traefik.http.services.server.loadbalancer.server.port=3000"

    client:
        container_name: client
        build:
            context: ./client
        ports:
            - "8080:80"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.client.rule=Host(`coolify.io`)"
            - "traefik.http.routers.client.entrypoints=http"
            - "traefik.http.services.client.loadbalancer.server.port=8080"