version: '3.8'

services:
  server:
    container_name: server
    build:
      context: ./server
    environment:
      - ORIGIN=${ORIGIN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rule=Host(`coolify.io`) && PathPrefix(`/api`)"
      - "traefik.http.routers.entrypoints=http"
  client:
    container_name: client
    build:
      context: ./client
    environment:
      - VITE_APP_API_URL=${VITE_APP_API_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rule=Host(`coolify.io`) && PathPrefix(`/`)"
      - "traefik.http.routers.entrypoints=http"