services:
    server:
        container_name: server
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "3001:3000"

    client:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "8081:80"
