version: '3.8'
services:
  server:
    container_name: server
    env_file:
      - .env
    build:
      context: ./server
    environment:
      - ORIGIN=${ORIGIN}
    labels:
        - traefik.enable=true
        - "traefik.http.routers.server.rule=Host(`thescrumplanning.site`) && PathPrefix(`/api/`)"
        - "traefik.http.routers.server.entryPoints=http,https"
        - "traefik.http.middlewares.svc-websocket.headers.customrequestheaders.Connection=Upgrade"
        - "traefik.http.middlewares.svc-websocket.headers.customrequestheaders.Upgrade=websocket"
        - "traefik.http.routers.server.middlewares=svc-websocket@docker"
        - "traefik.http.routers.server.middlewares=svc-websocket@docker"
  client:
    container_name: client
    env_file:
      - .env
    build:
      context: ./client
      dockerfile: Dockerfile
    args:
      - VITE_API_URL=${VITE_API_URL}
    labels:
        - traefik.enable=true
        - "traefik.http.routers.client.rule=Host(`thescrumplanning.site`) && PathPrefix(`/`)"
        - "traefik.http.routers.client.entryPoints=http,https"