version: '3.8'

services:
  server:
    container_name: server
    build:
      context: ./server
    environment:
      - ORIGIN=${ORIGIN}
    labels:
        - traefik.enable=true
        - "traefik.http.routers.server.rule=Host(`thepokerplanning.com`) && PathPrefix(`/api`)"
        - "traefik.http.routers.client.entryPoints=http,https"
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.debug
    environment:
      - VITE_APP_API_URL=${VITE_APP_API_URL}
    labels:
        - traefik.enable=true
        - "traefik.http.routers.client.rule=Host(`thepokerplanning.com`) && PathPrefix(`/`)"
        - "traefik.http.routers.client.entryPoints=http,https"