version: '3.8'

services:
  server:
    container_name: server
    build:
      context: ./server
    environment:
      - ORIGIN=${ORIGIN}
    labels:
        - traefik.enable=true
        - "traefik.http.routers.server.rule=Host(`thepokerplannig.com`) && PathPrefix(`/api`)"
        - traefik.http.routers.server.entryPoints=http
  client:
    container_name: client
    build:
      context: ./client
    environment:
      - VITE_APP_API_URL=${VITE_APP_API_URL}
    labels:
        - traefik.enable=true
        - "traefik.http.routers.client.rule=Host(`thepokerplannig.com`) && PathPrefix(`/`)"
        - traefik.http.routers.client.entryPoints=http