version: '3.8'

services:
  server:
    container_name: server
    app:
      env_file:
        - .env
    build:
      context: ./server
    environment:
      - ORIGIN=${ORIGIN}
    labels:
        - traefik.enable=true
        - "traefik.http.routers.server.rule=Host(`thepokerplanning.com`) && PathPrefix(`/socket.io/`)"
        - "traefik.http.routers.client.entryPoints=http,https"
        - "traefik.http.middlewares.svc-websocket.headers.customrequestheaders.Connection=Upgrade"
        - "traefik.http.middlewares.svc-websocket.headers.customrequestheaders.Upgrade=websocket"
        - "traefik.http.routers.server.middlewares=svc-websocket@docker"
  client:
    container_name: client
    app:
      env_file:
        - .env
    build:
      context: ./client
      args:
        - vite_api_url: ${vite_api_url}
    environment:
        - VITE_API_URL=${vite_api_url}
    labels:
        - traefik.enable=true
        - "traefik.http.routers.client.rule=Host(`thepokerplanning.com`) && PathPrefix(`/`)"
        - "traefik.http.routers.client.entryPoints=http,https"